Repository hashicorp/packer-plugin-tencentcloud, pull requests merged in 2023-06, with the labels that each got.

#104 cleanup github workflows
  .github/workflows/test-plugin-example.yml
Labels: tech-debt

#105 Add `image_tags` attribute for setting tags on the created image
  builder/tencentcloud/cvm/builder.hcl2spec.go
  builder/tencentcloud/cvm/image_config.go
  builder/tencentcloud/cvm/image_config_test.go
  builder/tencentcloud/cvm/step_create_image.go
  docs-partials/builder/tencentcloud/cvm/TencentCloudImageConfig-not-required.mdx
  example/build.pkr.hcl
Labels: enhancement

#97 cvm: fix tag/field SkipImageValidation conflicts
  builder/tencentcloud/cvm/access_config.go
  builder/tencentcloud/cvm/access_config_test.go
  builder/tencentcloud/cvm/builder.go
  builder/tencentcloud/cvm/builder.hcl2spec.go
  builder/tencentcloud/cvm/image_config.go
  builder/tencentcloud/cvm/image_config_test.go
  docs-partials/builder/tencentcloud/cvm/TencentCloudAccessConfig-not-required.mdx
  docs-partials/builder/tencentcloud/cvm/TencentCloudImageConfig-not-required.mdx
  go.mod
  go.sum
Labels: bug
